// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTSkkrdATzL1tXP2Q9pMzAA94rnix229A',
    appId: '1:909403253151:web:4cf2de8e7d3be5c3f135aa',
    messagingSenderId: '909403253151',
    projectId: 'todo-1d472',
    authDomain: 'todo-1d472.firebaseapp.com',
    storageBucket: 'todo-1d472.appspot.com',
    measurementId: 'G-2BLV4MVZNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCERIgQ4UBlJtpXK2uhfAeDbb5f7LKz4hs',
    appId: '1:909403253151:android:6877bdedb44d93e2f135aa',
    messagingSenderId: '909403253151',
    projectId: 'todo-1d472',
    storageBucket: 'todo-1d472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXFvxrHb2Jn80tmC-C8TWPfr4MDVgqq6s',
    appId: '1:909403253151:ios:acdaa4b2c53e03a4f135aa',
    messagingSenderId: '909403253151',
    projectId: 'todo-1d472',
    storageBucket: 'todo-1d472.appspot.com',
    iosBundleId: 'com.example.toDoGfg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXFvxrHb2Jn80tmC-C8TWPfr4MDVgqq6s',
    appId: '1:909403253151:ios:590708b595ffa5e0f135aa',
    messagingSenderId: '909403253151',
    projectId: 'todo-1d472',
    storageBucket: 'todo-1d472.appspot.com',
    iosBundleId: 'com.example.toDoGfg.RunnerTests',
  );
}
